apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: devflow-tekton-git-clone
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: devflow
    app.kubernetes.io/component: tekton-task
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: main
  results:
    - name: commit
      description: git commit SHA
      type: string
  workspaces:
    - name: output
    - name: ssh
  steps:
    - name: clone
      image: mcp/git:latest
      script: |
        mkdir -p ~/.ssh
        cp $(workspaces.ssh.path)/id_rsa ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git clone $(params.url) $(workspaces.output.path)
        cd $(workspaces.output.path)
        git checkout $(params.revision)
        git rev-parse HEAD | tee $(results.commit.path)
