apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devflow-release-service-tekton
  namespace: tekton-pipelines
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list", "patch", "update", "delete"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines"]
    verbs: ["get", "list"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "list", "watch"]
