// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/intents": {
            "get": {
                "description": "按 kind、status、resource、application 等维度查询 execution intents",
                "tags": [
                    "Intent"
                ],
                "summary": "获取执行意图列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Intent"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/intents/{id}": {
            "get": {
                "tags": [
                    "Intent"
                ],
                "summary": "获取执行意图",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Intent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Intent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/manifests": {
            "get": {
                "tags": [
                    "Manifest"
                ],
                "summary": "获取应用列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Manifest"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "根据 Manifest 创建 Manifest，自动生成名称",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manifest"
                ],
                "summary": "创建 Manifest",
                "parameters": [
                    {
                        "description": "Manifest 数据（branch 必填）",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Manifest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/manifests/{id}": {
            "get": {
                "tags": [
                    "Manifest"
                ],
                "summary": "获取应用",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Manifest ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Manifest"
                        }
                    }
                }
            },
            "patch": {
                "description": "部分更新 Manifest（仅支持 digest / commit_hash）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Manifest"
                ],
                "summary": "Patch Manifest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Manifest ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patch 数据",
                        "name": "data",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.PatchManifestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/releases": {
            "get": {
                "tags": [
                    "Release"
                ],
                "summary": "获取Release列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Release"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的Release",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Release"
                ],
                "summary": "创建Release",
                "parameters": [
                    {
                        "description": "Release Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Release"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreateResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/releases/{id}": {
            "get": {
                "tags": [
                    "Release"
                ],
                "summary": "获取Release",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Release ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Release"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateResponse": {
            "type": "object",
            "properties": {
                "execution_intent_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "model.ConfigMap": {
            "type": "object",
            "properties": {
                "files_path": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "mount_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.EnvVar": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "model.Intent": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "string"
                },
                "application_name": {
                    "type": "string"
                },
                "attempt_count": {
                    "type": "integer"
                },
                "branch": {
                    "type": "string"
                },
                "claimed_at": {
                    "type": "string"
                },
                "claimed_by": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "external_ref": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "$ref": "#/definitions/model.IntentKind"
                },
                "last_error": {
                    "type": "string"
                },
                "lease_expires_at": {
                    "type": "string"
                },
                "manifest_id": {
                    "type": "string"
                },
                "manifest_name": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "release_id": {
                    "type": "string"
                },
                "release_type": {
                    "type": "string"
                },
                "repo_url": {
                    "type": "string"
                },
                "resource_id": {
                    "type": "string"
                },
                "resource_type": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.IntentStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.IntentKind": {
            "type": "string",
            "enum": [
                "build",
                "release"
            ],
            "x-enum-varnames": [
                "IntentKindBuild",
                "IntentKindRelease"
            ]
        },
        "model.IntentStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed"
            ],
            "x-enum-varnames": [
                "IntentPending",
                "IntentRunning",
                "IntentSucceeded",
                "IntentFailed"
            ]
        },
        "model.Internet": {
            "type": "string",
            "enum": [
                "internal",
                "external"
            ],
            "x-enum-varnames": [
                "Internal",
                "External"
            ]
        },
        "model.Manifest": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "string"
                },
                "application_name": {
                    "type": "string"
                },
                "branch": {
                    "type": "string"
                },
                "commit_hash": {
                    "type": "string"
                },
                "config_maps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ConfigMap"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "digest": {
                    "type": "string"
                },
                "envs": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/model.EnvVar"
                        }
                    }
                },
                "execution_intent_id": {
                    "type": "string"
                },
                "git_repo": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "internet": {
                    "$ref": "#/definitions/model.Internet"
                },
                "name": {
                    "type": "string"
                },
                "pipeline_id": {
                    "type": "string"
                },
                "replica": {
                    "type": "integer"
                },
                "service": {
                    "$ref": "#/definitions/model.Service"
                },
                "status": {
                    "$ref": "#/definitions/model.ManifestStatus"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ManifestStep"
                    }
                },
                "type": {
                    "$ref": "#/definitions/model.ReleaseType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.ManifestStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed"
            ],
            "x-enum-varnames": [
                "ManifestPending",
                "ManifestRunning",
                "ManifestSucceeded",
                "ManifestFailed"
            ]
        },
        "model.ManifestStep": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.StepStatus"
                },
                "task_name": {
                    "type": "string"
                },
                "task_run": {
                    "type": "string"
                }
            }
        },
        "model.PatchManifestRequest": {
            "type": "object",
            "properties": {
                "commit_hash": {
                    "type": "string"
                },
                "digest": {
                    "type": "string"
                }
            }
        },
        "model.Port": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "target_port": {
                    "type": "integer"
                }
            }
        },
        "model.Release": {
            "type": "object",
            "properties": {
                "application_id": {
                    "type": "string"
                },
                "application_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "execution_intent_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "manifest_id": {
                    "type": "string"
                },
                "manifest_name": {
                    "type": "string"
                },
                "project_name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.ReleaseStatus"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ReleaseStep"
                    }
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.ReleaseStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed",
                "RollingBack",
                "RolledBack",
                "Syncing",
                "SyncFailed"
            ],
            "x-enum-varnames": [
                "ReleasePending",
                "ReleaseRunning",
                "ReleaseSucceeded",
                "ReleaseFailed",
                "ReleaseRollingBack",
                "ReleaseRolledBack",
                "ReleaseSyncing",
                "ReleaseSyncFailed"
            ]
        },
        "model.ReleaseStep": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/model.StepStatus"
                }
            }
        },
        "model.ReleaseType": {
            "type": "string",
            "enum": [
                "normal",
                "canary",
                "blue-green"
            ],
            "x-enum-varnames": [
                "Normal",
                "Canary",
                "BlueGreen"
            ]
        },
        "model.Service": {
            "type": "object",
            "properties": {
                "ports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Port"
                    }
                }
            }
        },
        "model.StepStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Running",
                "Succeeded",
                "Failed"
            ],
            "x-enum-varnames": [
                "StepPending",
                "StepRunning",
                "StepSucceeded",
                "StepFailed"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
